### ISSUE TITLE
Disable the Number to String automatic conversion

### ISSUE THREAD

**Issue by fabianpiau** [FasterXML/jackson-core#192]
By default, Jackson is converting numbers to strings. In most cases, that's fine. But not in my situation unfortunately. Is there a way to prevent that?

For example:

JSON
```json
{
"numberAsString": 123
}
```
JAVA
```java
private String numberAsString;
```

It works just fine. But the thing is that I want this automatic boxing not enabled and got an exception instead. So the user is forced to use a String. I.e.

```json
{
"numberAsString": "123"
}
```
I don't think such a feature exist, I look on http://wiki.fasterxml.com/JacksonFeaturesGenerator and a bit everywhere like http://stackoverflow.com/questions/7806316/jackson-json-converts-integers-into-strings

I tried to create a custom deserializer, but it seems that the value is already converted as a string when I got to the deserializer, and I don't have the possibility to determine if it was a string or an integer originally in the request.

Thanks

Fabian

**Comment by cowtowncoder** [comment]
Custom deserializer registered for `java.lang.String` should definitely work and let you prevent conversion. Deserializers will directly see content via `JsonParser` so they can detect underlying token type.

As to feature, that is a possibility. This feature request should actually go in:

https://github.com/FasterXML/jackson-databind/issues/

because it is related to binding of data from streaming JSON API (this project) into POJOs.
If you could re-create the request there that would be great; otherwise it may not get enough visibility.

**Comment by fabianpiau** [comment]
Thanks for your answer, I have created [the issue 796](https://github.com/FasterXML/jackson-databind/issues/796) in jackson-databind submodule.

I don't understand how to do it with the custom deserializer. Indeed, I see the content via JsonParser, but it is already seen as a String, well if I parse it as a int, I will see it at the int, but that will not help me. My point is to know what was the exact type in the JSON request. Is there any existing method that I am missing?

Perhaps you can reply on the new issue and close that one.

**Comment by cowtowncoder** [comment]
Thanks!
