### ISSUE TITLE
JsonInclude.Include.NON_NULL not works with JDK8's Optional and custom serializer

### ISSUE THREAD

**Issue by vicmosin** [FasterXML/jackson-core#193]
```java
@Data
@Builder
public class User extends Base {

    private String firstName;

    private String lastName;

    @JsonSerialize(using = OptionalBusinessSerializer.class)
    private Optional<Business> business;
}

public class OptionalBusinessSerializer extends JsonSerializer<Optional<Business>> {

    @Override
    public void serialize(Optional<Business> business, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException, JsonProcessingException {
        jsonGenerator.writeString(business.map(item -> item.getLinkForRel("self")).orElse(null));
    }
}

//REST client
ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new Jackson2HalModule());
mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

Once the business object is null - all the `null` values are removed from output JSON, otherwise the custom serializer being executed which might write correct value or null. In this case the output JSON contains the nulls.

What I need at the end: if business is null or Optional.empty or `business.map(item -> item.getLinkForRel("self")).orElse(null)` returns null  - JSON shouldn't contain business field.

**Comment by cowtowncoder** [comment]
(note: this should be reported for `jackson-databind`, at https://github.com/FasterXML/jackson-databind/issues -- but I'll add comments here first)

Try using `JsonInclude.Include.NON_EMPTY`, if you want to get rid of `Optional.absent()` values.
`Optional.absent()` is not considered null, as that only covers true Java `null`, and not referential types that do not refer to an object; but latter is considered "empty".
This behavior of `Optional` values works as intended and not a bug.

Note, however, that if you use custom serializers, you must handle all serialization yourself.
You can not suppress output of properties from within `JsonSerializer.serialize()`, because at that point property name has already been written out.

But if you want more complex filtering rules, you may override method `isEmpty()` in  `JsonSerializer` -- this gets called by POJO serializer when determining whether value of a property is considered "empty", for purposes of serialization. This should allow using more advanced rules for exclusion.

**Comment by vicmosin** [comment]
Thanks, understood.
