### ISSUE TITLE
Need access to Generator's _outputTail

### ISSUE THREAD

**Issue by RuedigerMoeller** [FasterXML/jackson-core#195]
Hi there,
I am currently implementing Json serialization (fast-serialization) using jackson-core as parser/generator backend. I am using the byte position in the outputstream to uniquely identify objects inside the stream (for ref-restoring).
Unfortunately i cannot access the _outputTail so i have to flush() the generator each time i need the output position to grab the write byte position from the underlying outputstream. This is quite costly according to my profiling, so it would by great if there was a method like getOutputPosition() or so.
(Note: it's workaroundable using some ugly patching + overriding, kudos for having most things 'protected' ;) )

**Comment by cowtowncoder** [comment]
Sounds reasonable. And yes, nowadays I default to `protected` since I have noticed that while sub-classing is not easy or clean way of doing this, it leaves a kind of fallback option open. :-)

One question on addition: how generic is this functionality? Since char- and byte-backed implementations vary, I am not sure whether it belongs in `JsonGenerator`, or on a sub-class.

Also: is the use case such that you access nominal byte location, and then this would be subtracted from that, to know how much has actually been sent to underlying stream?
I guess I am just interested in seeing how you would use this method to make sure addition works as expected.

**Comment by RuedigerMoeller** [comment]
Thanks for quick response !
generic: I can't say. I need the physical byte location regardless of encoding
addition: as i control the underling inputstream, i can compute full file location by adding inputstream.byteswritten+generator._outputTail. At read time i build up a map <streampos:object> so i can resolve references.
I'll update my dependency + remove my workaround once this one is released. Thx in advance :-)

**Comment by cowtowncoder** [comment]
Ok. So it's sort of "return number of unflushed units [byte or char] of output content". If so, I can add it generically for both backends.

In a way it might make sense to expose "read but not decoded" for input side. But one feature at a time. :)

**Comment by RuedigerMoeller** [comment]
thought about your "genericity" remark. Actually relying on byte position is not a good idea for text based encodings as this raises the restriction that the same charset and formatting (+cr/lf style) has to be used at read and write side, using kind of a token count would be more appropriate. 
Anyway the serialization impl currently still "thinks" its writing binary, so streamposition is used both for doing byte[] copy stuff and object identification, midterm i will have to separate these logically. But one feature at a time :-)

**Comment by cowtowncoder** [comment]
Implemented, please let me know if it does what is expected.

**Comment by cowtowncoder** [comment]
Right. I added notes that the value will be in whatever internal units are being used, since byte amount can not be known before encoding, which may need to be done after flushing (when using `Writer`).
For completeness sake it'd make sense to add another accessor to figure out type (char vs byte), but for now that's more speculative as it is not clear that this would be useful for non-byte-based sources anyway.
