### ISSUE TITLE
Unable to override writeObjectFieldValueSeparator in DefaultPrettyPrinter

### ISSUE THREAD

**Issue by chuwy** [FasterXML/jackson-core#199]
I tried to override `writeObjectFieldValueSeparator` method to output colon without space before it, like it described in [Jackson Cookbook](http://samples.leanpub.com/jacksoncookbook-sample.pdf
) in "Custom Pretty Printer":

```java
@Override
public void writeObjectFieldValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException {
    jg.writeRaw(": ");
}
```
And it seems it does not even called (judging by print statements).
On the other hand, this trick with ``MinimalPrettyPrinter`` works fine.

**Comment by cowtowncoder** [comment]
I would need a unit test to reproduce this.

**Comment by chuwy** [comment]
Ok. I'll provide it tomorrow.
Until now only this solutions works for me: https://gist.github.com/chuwy/84ed38389b50d766f17f which isn't looks good anyway.

**Comment by maxshort** [comment]
I think this due to the fact that `DefaultPrettyPrinter` is of type `Instantiable` which means it has a `createInstance` method which is meant to copy the `DefaultPrettyPrinter`.  `ObjectWriter` calls `createInstance` on the extended `CustomPrettyPrinter` which returns a `DefaultPrettyPrinter`.

The reason that the gist above works is that it overrides `createInstance`. Not sure if this is a bug or just needs more documentation.

**Comment by cowtowncoder** [comment]
@maxshort Good point -- `createInstance()` absolutely does need to be overridden, both to return proper subtype instance when it is called, and (if implementation just returned `this`), to avoid clashes.

@chuwy I think explanation above is correct: you need to override `createInstance()` to return instance of your sub-class.
