### ISSUE TITLE
@ApiModelProperty(hidden=true) removes field from serialization

### ISSUE THREAD

**Issue by weaselmetal** [FasterXML/jackson-core#219]
When I decorate a getter with @ApiModelProperty(hidden=true) (from io.swagger.annotations), the field is also excluded from jackson's serialization. This was pretty surprising, assuming that the annotation would only omit documentation of that element, not removing it from serialization.
We are using version 2.4.6.

**Comment by cowtowncoder** [comment]
Possible, but without actual bug in `jackson-core`, shouldn't this be filed against Swagger module?
If the issue (whatever it is) can be reproduced with snipped from swagger module, it may be filed against `jackson-databind`, since that implements annotation processing functionality.

**Comment by weaselmetal** [comment]
Sorry, wasn't sure which project fits best. With swagger module you mean the https://github.com/FasterXML/jackson-module-swagger project, right?
Well, since actually the serialization is affected, jackson-databind would be probably the right project?

**Comment by cowtowncoder** [comment]
@weaselmetal Thing is that databind does not use or recognize `@ApiModelProperty` in any way, so the investigation needs to start with whatever uses it (which I assumed was Swagger module?).
It may be that something within databind is ultimately problematic, and then an issue should be filed against `jackson-databind`, definitely. But since the problem first surfaces with something else, it is not the starting point.
