### ISSUE TITLE
Support Relative JSON Pointers

### ISSUE THREAD

**Issue by adjohnson916** [FasterXML/jackson-core#228]
https://tools.ietf.org/html/draft-luff-relative-json-pointer-00

**Comment by cowtowncoder** [comment]
I doubt this will be added, due to couple of reasons. First of all, it requires access to the whole document, as it traverses back in parent axis, and this is not something streaming access can offer. In addition, Jackson's default tree model (included in `jackson-databind`) does not have parent-linkage, so to support such traversal an alternate tree model would be needed.

So this is probably something to support outside of Jackson itself.

**Comment by adjohnson916** [comment]
@cowtowncoder Yes, I think it wouldn't be part of the streaming API. We already support `JsonPointer` and the `TreeNode at(JsonPointer ptr)` method in the public API that operates on in-memory trees. We could consider also supporting a method like:
```TreeNode at(JsonPointer startPtr, JsonPointer relativePtr)```

**Comment by cowtowncoder** [comment]
Forgot to first say thank you for reporting this -- it's good to know about new developments.

As to my comments; what I mean is that unfortunately the processing model for that spec requires ability to traverse tree model in parent direction; and supporting that is difficult.
It may be the case that pointer expression itself could perhaps be supported, and if so, that may make sense. But evaluating such expressions would require additional tree model (parent linked one), and perhaps new project/module.

So I am not against adding support for new standards as relevant, just pointing out practical challenges.

Another idea: it may make sense to file requests like this under main `jackson` project (I enabled issue tracker for it few days ago) -- that would allow discussions for things for which there may not be immediate "home". I understand that since `jackson-core` provides `JsonPointer` base implementation this project makes sense here, but there are often things for which it is not as clear cut.
