### ISSUE TITLE
Enabled PrettyPrinting is ignored when writing custom Json

### ISSUE THREAD

**Issue by d-schmidt** [FasterXML/jackson-core#247]
example 2.7.0:

```java
    private static class Foo {
        String bar = "baz";
    }

    public static void main(String[] args)
            throws IOException {
        ObjectMapper baseMapper = new ObjectMapper().setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
        ObjectMapper indentMapper = baseMapper.copy().enable(SerializationFeature.INDENT_OUTPUT);

        // pojo; indent enabled
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        JsonGenerator jg = indentMapper.getFactory().createGenerator(out, JsonEncoding.UTF8);
        jg.writeObject(new Foo());
        System.out.println(new String(out.toByteArray()));

        // custom json; indent enabled
        out = new ByteArrayOutputStream();
        jg = indentMapper.getFactory().createGenerator(out, JsonEncoding.UTF8);
        jg.writeStartObject();
        jg.writeStringField("bar", "baz");
        jg.writeEndObject();
        jg.flush();
        System.out.println(new String(out.toByteArray()));

        // custom json; reset printer
        out = new ByteArrayOutputStream();
        jg = indentMapper.getFactory().createGenerator(out, JsonEncoding.UTF8).useDefaultPrettyPrinter();
        jg.writeStartObject();
        jg.writeStringField("bar", "baz");
        jg.writeEndObject();
        jg.flush();
        System.out.println(new String(out.toByteArray()));
    }
```

output:

```json
    {
      "bar" : "baz"
    }
    {"bar":"baz"}
    {
      "bar" : "baz"
    }
```

expected output:

```json
    {
      "bar" : "baz"
    }
    {
      "bar" : "baz"
    }
    {
      "bar" : "baz"
    }
```

I suppose this is a bug and not a feature. I can't find any documentation explaining this behavior.

**Comment by cowtowncoder** [comment]
This does seem like a bug yes. I suspect this may be related to this line:

    jg = indentMapper.getFactory().createGenerator(out, JsonEncoding.UTF8).useDefaultPrettyPrinter();

where it may be the case that trying to attach the default pretty printer after construction of generator was not working.

Which version does this happen with?

**Comment by d-schmidt** [comment]
This is bugged at least in 2.6.5 and 2.7.0.
Calling `jg.getPrettyPrinter()` returns null but the pojo mapper is still working. After some code inspection I noticed `writeStartObject()` and `writeObject(new Foo())` are implemented in different inheritance layers/levels.

**Comment by cowtowncoder** [comment]
Hmmh. I'll have to take back my earlier comment; this is probably not a bug.

The problem here is the interaction of `SerializationFeature.INDENT_OUTPUT` and `JsonGenerator` creation. Specifying this feature will affect the way `ObjectMapper` and `ObjectWriter` work: basically, when they construct `JsonGenerator`, they will call `JsonGenerator.useDefaulPrettyPrinter()` (or, depending, `setPrettyPrinter()` with default pretty printer instantiated).
But this can not be done in the case that you directly access `JsonFactory` and construct `JsonGenerator` manually.

In this case, you will need to call `useDefaultPrettyPrinter()` (or explicit set pretty printer), as mapper is not involved.

I hope this helps.

**Comment by d-schmidt** [comment]
If it is not a bug, it is just bad. Mixing POJO and normal writing like:

    ByteArrayOutputStream out = new ByteArrayOutputStream();
    JsonGenerator jg = indentMapper.getFactory().createGenerator(out, JsonEncoding.UTF8);
    jg.writeStartObject();
    jg.writeObjectField("foo", new Foo());
    jg.writeEndObject();    
    System.out.println(new String(out.toByteArray()));

results in "ugly", partly formatted json.

**Comment by cowtowncoder** [comment]
@d-schmidt It is a limitation due to separation of components. You are setting a property of `jackson-databind`, but when you access `JsonFactory` (which comes from `jackson-core` and has no awareness of databind, being at lower level) this setting can not have any effect -- `ObjectMapper` is not involved in any way.

Your example above does the same thing: it will not work without your explicitly calling `useDefaultPrettyPrinter` on `JsonGenerator` constructed. Just because you access `JsonFactory` via `ObjectMapper` can not configure pretty printing.
