### ISSUE TITLE
Jackson improperly serializes/deserializes MAX_LONG

### ISSUE THREAD

**Issue by glajchs** [FasterXML/jackson-core#261]
I'm using version 2.2.4 but looking at the code path this hasn't changed as far as I can tell.

Jackson is casting longs to doubles when serializing and deserializing.  This is causing issues for us.
This turns java's max long from 9223372036854776000 to 9223372036854775807 (193 less).  What's happening for us is that the value is getting serialized when we send it out (in this case to javascript on a web page) as 9223372036854775807.  In a weird series of events, it so happens that javascript can't store that much precision for integers and rounds it up to 9223372036854776000.  Then when this value sets sent back up to our server and deserialized, it throws an out of range for long exception (even though technically it is java's Long.MAX_VALUE.

Now I know that this series of events seems like an edge case, but it does still bring up the fact that once the object has left your java program and come back, it's value has been changed by Jackson and is no longer max long.  If you were using max long as a determination of special behavior, then that's now broken.

**Comment by cowtowncoder** [comment]
Jackson should not be casting longs to double unless it absolutely has to do that for some reason.
There are definitely problems doing such coercion as you correctly point out.
The only case where `double`s would be using is if Javascript value type is floating point (that is, has decimal point). You should also be able to force use of `BigDecimal` if necessary.

So I would need to have a reproducible test case, or, pointer to code to know the specific issue you have, since I can not think of a case where coercion would occur.

**Comment by cowtowncoder** [comment]
I would need a reproduction here, to be able to fix problems there may be. May be reopened with a test case.
