### ISSUE TITLE
Possible problem to obtain java.util.Date from javascript timestamp

### ISSUE THREAD

**Issue by matienzar** [FasterXML/jackson-core#275]
Hello,

  I don't know if this is a bug or I need to do something else.

 I have this javascript date:
   `new Date(1963,4,15,0,0,0,0)`

 If I obtain its toString, I get this:
`Wed May 15 1963 00:00:00 GMT+0200 (CET)`

If I obtain its getTime, I get this:
`-211946400000`

But if I obtain java.util.Date from Jackson I get 
`Sun Apr 14 23:00:00 CET 1963`

And if I do the same on linux OS, I get:
```
date --date @-211946400
dom abr 14 23:00:00 CET 1963
```
same results as jackson.

Why I can't get this date 1963/04/15 from Jackon for this timestamp: -211946400000?

We're using jackson 2.5.1 from wildfly 9.0.2.

Lot of thanks,

  Marcial

**Comment by cowtowncoder** [comment]
@matienzar Unfortunately Java `java.util.Date` does NOT retain any timezone information, for one, so timezone being seen varies a lot depending on settings. But aside from that, what matters most is the format you use in JSON  -- values in Javascript are not enough to know what happens, since data is read by Jackson from JSON, and that has all the information.
FWIW, Javascript can not deal with 64-bit timestamps as numbers (internally IEEE double, that is, 64-bit floating point number is always used; it does not have enough accuracy for 64-bit integers), so dates usually have to be sent using ISO-8601 format, or handled and passed as JSON Strings.

**Comment by cowtowncoder** [comment]
Ok; I need test code to exhibit problem to know what if anything is going wrong.
