### ISSUE TITLE
serialize CharSequence to string

### ISSUE THREAD

**Issue by radopas** [FasterXML/jackson-core#328]
It will be very useful that when an object contains CharSequence fields they to be serialized into string. At the moment CharSequence is serialized into [object Object]

**Comment by cowtowncoder** [comment]
I should think they are do that... do you have a test case to show this behavior?

**Comment by radopas** [comment]
Hello,
I checked some more situations and it looks that it works for most of the cases, but doesn't correctly serialize CharSequence when the passed instance is for example org.apache.commons.lang3.text.StrBuilder.

Here is a simple test i've made. It doesn't print the content of the CharSequence but a serialization of the object instance:

public class JsonTest {
  public static void main(String[] args) throws Exception {
    CharSequence charSequence = new org.apache.commons.lang3.text.StrBuilder("text");
    com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
    java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
    mapper.writeValue(out, charSequence);
    if (!out.toString().equals("\"text\"")) {
      throw new Exception("output is :" + out.toString() + " instead of \"text\"");
    }
  }
}

**Comment by cowtowncoder** [comment]
@radopas This is then because such type is recognized as a POJO, and unfortunately it is not safe to assume everything that implements `CharSequence` should be dealt with as such.
So unfortunately I don't think this is something that may be changed without potentially causing problems for some users.

If you do need to use `CharSequence` style serialization, you can add

`@JsonSerialize(as=CharSequence.class)`

which should force serialization using that type, regardless of other information.

But another thing that might help: as you may know there are many datatype modules that add explicit supports for various types. So would commons-lang3 module:

https://github.com/bramp/jackson-datatype-commons-lang3

help you? It sounds like that should help.

**Comment by cowtowncoder** [comment]
Actually... should have read README first. Seems like support is very limited.
However, perhaps its author would be open to additions?

**Comment by radopas** [comment]
Ok. For me, it sounds reasonable to treat all CharSequences as such (this is why the interface is implemented), but i understand that this may not be safe and could have side effects, so i'm closing this. I'll add the annotations in my code.

Thank you for the help:)

**Comment by cowtowncoder** [comment]
@radopas You would be surprised how many developers have implemented all kinds of add-on interfaces for convenience: for example, to make POJOs loggable via frameworks, and would report bugs for "stupid handling that considers these CharSequences". :-D
So while I agree that it seems more likely than not that intent is to indicate the thing as `CharSequence`, I do not trust it enough to default to it.

For what it is worth, similar issues are even more problematic with `Iterable` and `Iterator`, which consistently would make sense to use as indicators, but are hard to know as such for sure.

Anyway, I wish there was a safe way but at this point I think backwards compatibility rules.
