### ISSUE TITLE
[QUESTION] Extending WriterBasedJsonGenerator

### ISSUE THREAD

**Issue by rfoltyns** [FasterXML/jackson-core#340]
Any reason for WriterBasedJsonGenerator being final? "Overriding" any of the public/protected methods is possible only by copying the whole class and applying the mod..

**Comment by cowtowncoder** [comment]
I can't recall earlier reasoning, but in general it is recommended to use delegation via `JsonGeneratorDelegate` for augmenting functionality.

Although given that parser implementations were changed to be non-final, I don't think there's fundamental reason why this could not be made non-final -- it's more a convenience thing: use via sub-classing tends to be fragile thing and cause more breakages.

Still, I could be convinced to make this non-final in 2.9; just can't be in patch for earlier versions (since it's a non-trivial change wrt compatibility between patch versions).

**Comment by rfoltyns** [comment]
Fragility is a valid argument and one of the responsibilities of extender is to always have this argument in mind. We can't be sure if and how somebody cause the breakage, but we shouldn't limit him - it's his code at the end..
2.9 would be great. Would you like me to create a pull request?

**Comment by cowtowncoder** [comment]
@rfoltyns Thank you! I think this is a good start, and there's time to tweak it before 2.9.0 is released (no release candidates yet).
