### ISSUE TITLE
Jackson encoding and decoding invalid unicode?

### ISSUE THREAD

**Issue by devinrsmith** [FasterXML/jackson-core#350]
Should Jackson encode and decode strings that aren't unicode?

I've got some testing where Strings aren't encodable in UTF-8 or UTF-16, but seem to pass the Jackson encode / decode process just fine.

https://gist.github.com/devinrsmith/51f10cfdebc7c7b803aa6df4f13b097c

Is this expected behavior?

**Comment by cowtowncoder** [comment]
There was a lengthy debate on this (as one of many, many other) issue on JSON spec mailing list at some point, and there were people who suggested that since quoting/escaping allows such values, they should be accepted. I think more developers suggested the opposite that validation should fail. I don't think there was real consensus.
This assuming I understood this issue correctly, to refer to unpaired surrogate pairs.

My opinion is that ideally except would be thrown, at least by default. Perhaps a `JsonParser.Feature` could also be added to suppress such exception.

Implementation would be, however, quite hairy, I'm afraid. Problem is that this would require either buffering, or additional look ahead. Well, sort of: I think that part of the problem could be quite easily handled -- the case of incorrect ordering (second part of surrogate first).
But the opposite, valid first quoted surrogate character, followed by something else, may be bit trickier.

Anyway: I would like to be able to signal the problem and PRs would be welcome.
I may also try to tackle this myself if I find time, perhaps by incremental improvements (I think it is ok to start with imperfect checks).
