### ISSUE TITLE
ByteQuadsCanonicalizer.TableInfo always empty?

### ISSUE THREAD

**Issue by CodingFabian** [FasterXML/jackson-core#386]
This is more of a question rather than a concrete issue, but maybe hinting at an issue, so I am reporting it.
I inspected several heap dumps of applications over the last days, and in all of them

com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.TableInfo
contained by this path:
![screen shot 2017-07-14 at 14 36 41](https://user-images.githubusercontent.com/176132/28212486-ea9e9bb0-68a1-11e7-8431-16474a53b577.png)
is empty.
I have not found a single instance where the table info is filled.
Is that correct? Maybe because we do not parse a certain type of data? Or is there a bug?

Feel free to close if this is working as intended.

**Comment by cowtowncoder** [comment]
First question would be whether you are using byte-based source or not: it would not be used, for example, when decoding from `Reader` or `String`.

But assuming you are, the second part is that fresh `TableInfo` is only merged if `JsonParser` is closed (either explicitly, or implicitly by end-of-input).

Otherwise instance held by `JsonFactory` really should not be empty. New instances are created from `release()` method in `ByteQuadsCanonicalizer`, called by `_releaseBuffers` in parser.

So... not sure why you'd see empty instances.

**Comment by CodingFabian** [comment]
All our Json Parsin is actually happening with "InputStream" as input.
And we close both input stream and parser with try with resoures

**Comment by cowtowncoder** [comment]
Hmmh. That is quite curious then. It would seem like contents should not be empty.

I have mostly tested this indirectly as part of performance tests, but those use small symbol tables (i.e. no expansion). I wonder if different scenarios work (or don't).

**Comment by CodingFabian** [comment]
thats why I felt this might be worth reporting. I cannot share the heapdumps, but is there anything I could look or to provide hints?

**Comment by CodingFabian** [comment]
![screen shot 2017-07-17 at 10 08 50](https://user-images.githubusercontent.com/176132/28259729-f6d9b3f0-6ad7-11e7-9a8d-ce8271b47992.png)

Usage of the 11 ones:
* 4x ObjectMapper which readTree a io.netty.buffer.ByteBufInputStream.ByteBufInputStream(ByteBuf) 
* ObjectMapper which readValue a java.io.File (YAML extension)
* 6x ObjectMapper which readTree a io.netty.buffer.ByteBufInputStream.ByteBufInputStream(ByteBuf)

**Comment by cowtowncoder** [comment]
I wish I could suggest, but I think the way I'd approach it probably would rely on low-tech things like printing out info during life cycle of `TableInfo` instances (when attempting to merge with parent etc).
Another thing would be to do this with 2.9.0(.pr4), since I probably won't change handling for earlier versions anyway -- not that behavior here has changed.

Right now I don't have time to look into this unfortunately, but once 2.9.0 is out (by end of July), I will want to come back.

**Comment by cowtowncoder** [comment]
Not sure what to do with this; might be worth checking if situation still the same with 2.10.
But closing for now; may be reopened with new relevant information.
