### ISSUE TITLE
Request for a canSkipChildren check for non-blocking parser.

### ISSUE THREAD

**Issue by adamjryan** [FasterXML/jackson-core#396]
Hi, presently there is a method for JsonParser named skipChildren and for the non-blocking parser if there is insufficient data to perform this operation (parse and discard all fields for the current json object) then it throws an exception as it leaves the stream in an inconsistent state.

It would be useful therefore to check whether this operation can be performed before doing so.
This check also has a second use which is to check whether the current object can be parsed synchronously without blocking, which can help to avoid failures with deserialisers that expect to operate synchronously.

I imagine the change would require the parser to scan ahead while maintaining a it's current parsing position so might lead to a bit of additional buffering.

**Comment by cowtowncoder** [comment]
Possibly not sufficient, but there is method `JsonParser.canParseAsync()` which can be used to see if we have non-blocking instance.

Other than this, I did have initial plans for `peekToken()` see #375.

However: I do not think it will be practical to support same for full entity (Object, Array).

**Comment by adamjryan** [comment]
Ah yeah I suppose if peekToken() is not a simple case at present this might be asking a but much at this stage, it's good see the initial implementation for non-blocking parsing anyway, cheers.
Might be good to leave this open if it becomes more feasible in the future.

**Comment by cowtowncoder** [comment]
@adamjryan I think implementing `peekToken()` may be doable but was deferred due to it being non-trivial. It could perhaps be added in 3.0 (next version). What I don't think is possible is implementation of anything like `skipChildren()` (or something that'd try to read enough tokens to support non-blocking reads for sub-trees). Instead I think I'd suggest using `TokenBuffer` (from `jackson-databind`) for buffering, and having helper method(s) (or entity that could control it). That can be made to work, but I don't see immediately obvious way to nicely layer that on `jackson-core`.

**Comment by adamjryan** [comment]
Actually TokenBuffer would work, the tokens can be read into it from JsonParser keeping track of the start/end blocks and when they even out the TokenBuffer can be passed to the synchronous deserialiser  using TokenBuffer.asParser().
Cool, thanks.
