### ISSUE TITLE
Wrong JsonLocation row/column for UncrecognizedPropertyException

### ISSUE THREAD

**Issue by coberleyv** [FasterXML/jackson-core#399]
When serializing data that is mapped using the @JsonCreator/@JsonProperty annotations, and when an unknown property is encountered, the JsonLocation row indicated in the exception message is not correct (See attached test case). Also, for simple deserialization scenarios where the row is correct, the column location is not what I would expect. I would expect the column to indicate the beginning of the property name, but it doesn't.
[LocationTest.java.zip](https://github.com/FasterXML/jackson-core/files/1301014/LocationTest.java.zip)

**Comment by cowtowncoder** [comment]
And this is for Jackson version.... ?

**Comment by coberleyv** [comment]
Sorry, forgot to mention that ... noticed in production at version 2.7.5. Reproduced and created test case with 2.9.1

**Comment by cowtowncoder** [comment]
Thank you for updated info. One note: since you are using annotations etc, this issue may belong under `jackson-databind` (since we couldn't add test case here). But it's ok for now.

One typical challenge with Creator properties, and something we probably won't be able to solve any time soon, is that buffering is often needed. Since locations are dynamically accessed, and since construction and retaining of `JsonLocation` has non-trivial cost (if done for each and every token), this tends to lead to location of buffered tokens not really being accurate -- it either refers to current location within stream (ahead), or, if choose to, location of the first token that was buffered.

It would perhaps be possible to add a `DeserializationFeature.EXACT_LOCATIONS` or such, which would start keeping token-by-token track, although that'd have to work through `TokenBuffer` to ensure they are retained (unless we'd be ok with location of first token of every value -- for scalars that's the only location, for Objects opening `{` etc).

**Comment by cowtowncoder** [comment]
Needs to go under `jackson-databind`.
