### ISSUE TITLE
Greeting and something about contributing code for Performance Enhancement in com.fasterxml.jackson.core.io.appendQuoted 

### ISSUE THREAD

**Issue by xinzhg** [FasterXML/jackson-core#406]
Hi guys,

During the usage of Jackson-core library. I found the com.fasterxml.jackson.core.io.appendQuoted is our hot path method. It was called hundreds of thousands of times. Then, I improve the performance of it by using unrolling for loop, which achieves almost 50% less of cost time. I think it will help other people who are using the Jackson-core library. So, I was wondering how can I contribute my code to Jackson-core.

Thanks,
Xin

**Comment by cowtowncoder** [comment]
Contributions are always welcome. If it is a small change, appending changed code or diff here in issue would work; otherwise a Pull Request (fork, change, create Pull Request) is probably best.
I would want to verify performance improvement (f.ex with https://github.com/FasterXML/jackson-benchmarks) to make sure there is improvement, since profiler results do not always correlate well with actual performance.

As to change, I guess it's one of methods in:

* src/main/java/com/fasterxml/jackson/core/io/SerializedString
* src/main/java/com/fasterxml/jackson/core/io/CharTypes

of which first seems more likely candidate.

**Comment by xinzhg** [comment]
Hi cowtowncoder,

Thank you for you reply.
I modified code inside CharTypes. I checked out the benchmark, I did not find any test case for testing CharTypes methods, Do I need to create some test case? Or I miss the test case which is already in the benchmark?

Thanks,
Xin

**Comment by cowtowncoder** [comment]
Oh. This method seems to be only called from `TextNode`, so should only change results for specific case of serializing nodes using `toString()`... which is not a very common use case (in fact, one should not use that for serializing except for debugging purposes).
So for all production use I would strongly recommend using `ObjectMapper.writeValue()` for serialization, even in case of `JsonNode`s.

But as performance testing: I do not use micro-benchmarks for specific areas but rather full serialization/deserialization tests, run using `jmh`. Problem with smaller tests is that they do not necessarily give much information on overall significant of changes; improving performance of operation that does not contribute much to the overall performance is less useful than optimizing something that gets used a lot. So I want improvements to show up on actual read and write tests: `jackson-benchmarks` has those. It is not the only test, but one I use for regression testing.

However: if use case is getting `String` out of `JsonNode`s, that is actually not performance tested anywhere. It should be quite easy to add new case, however.

**Comment by xinzhg** [comment]
Hi cowtowncoder,
Thank you for your reply.
Yes, from hprof, I found it is used by TextNode. The reason we use toString() is for enriching and reformatting the data with other information and merge them to a bigger json and also we are still using 2.5.x, and I realized that the 2.9.x has some different apis from 2.5.x. 
For the performance, I create a test case inside the benchmarks in my repo, which is I fork from your repo. It can save more than 1 second in the benchmark in the case of 1 million records, the cost of time without .

**Comment by cowtowncoder** [comment]
Ok. I appreciate your help here, but I do not think this method should ever be on critical path.
You really should not use `JsonNode.toString()` for any JSON manipulation -- it is not guaranteed to produce valid JSON, even, much less perform efficiently. You would be better off using Jackson's real JSON serialization functionality; not trying to combine Strings together.

So: it is possible that unrolling would improve performance. But it adds code, making it less readable. I don't think it makes sense to do that for something that should not be a performance bottleneck.

I may also change Jackson 3.x so that `JsonNode.toString()` will explicitly produce something other than legal JSON, to make sure users do not use it accidentally -- like all cases of `toString()`, it should only ever be used for diagnostics, not for serialization.

**Comment by xinzhg** [comment]
Hi cowtowncoder,

Thank you for your reply.
Just share the code https://github.com/xinzhg/jackson-core/commit/d6f57c4446edc370c2d525c0b41b372a22bdf2bd

Thanks,
Xin
