### ISSUE TITLE
Missing new version's release notes

### ISSUE THREAD

**Issue by sfragata** [FasterXML/jackson-core#430]
Hi, the last release notes was for 2.9.1

https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x

Could you update it ?

Thanks

**Comment by cowtowncoder** [comment]
Release notes can be found from `2.9` branch, and main Jackson repo wiki also has those:

https://github.com/FasterXML/jackson/wiki/Jackson-Releases

The problem is that I don't thing git merge can reconcile files any more, although perhaps I could try renaming version file in 2.9 branch... I'll see if that works, that would probably be an improvement.
