### ISSUE TITLE
`ArrayIndexOutOfBoundsException` in `UTF8StreamJsonParser`

### ISSUE THREAD

**Issue by lislon** [FasterXML/jackson-core#437]
Using of UTF8StreamJsonParser#nextToken for closed JsonParser causes unmeaningfull ArrayIndexOutOfBoundsException exception. 

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2940)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:968)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParserTest.testExceptionOnClosedParserOnNextFieldName(UTF8StreamJsonParserTest.java:19)
```

I spent quite a lot of time to debug this and propose to add a meaningfull exception for this case. The code that causes this exception looks like this
```java
// pseudocode
Iterable<SomeData> getData() {
  try {
      jsonParser = jsonFactory.createParser(stream)
      return jsonParser.readValuesAs(SomeData.class);
  } finally {
     jsonParser.close();
  }
}
```
What do you think if we could add a check for this case and throw meaningfull exception?

**Comment by cowtowncoder** [comment]
Just to make sure I understand...

First, I agree, attempt to `close()` should never throw exception like this.

But second, I think it should be fine to call `close()` multiple times: this should not throw exceptions. So operation should be idempotent. This because it can be non-trivial to track state, and it seems silly to have to, say, call `if (!p.isClosed()) { p.close(); }` or such.
It really should not throw exception simply because it's called more than once (there could be other reasons for `IOException` but not this one).

Does this make sense?

**Comment by cowtowncoder** [comment]
Ah. My earlier comment was based on my misunderstanding wrt problem.

I think that trying to read from a closed parser should either throw a meaningful exception, or, possibly, return `null`. Either fix would be acceptable.

**Comment by cowtowncoder** [comment]
Thank you for the patch (merged). I made a minor change to fix itself to achieve same result without adding closed check within `nextXxx()` methods. Fix will be in 2.9.4.

**Comment by lislon** [comment]
Ok, Thank you :+1:

**Comment by cowtowncoder** [comment]
Thank you for reporting & fixing this!
