### ISSUE TITLE
Request publication of release 2.6.7.1 and 2.6.7.2  in Maven central repository

### ISSUE THREAD

**Issue by based2** [FasterXML/jackson-core#457]
http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6.7.x

**Comment by cowtowncoder** [comment]
You may have misunderstood the point of micro-patch releases. By design they only apply to a single component -- in this case, `jackson-databind` -- and there is no full set of components. For other components regular last patch release is to be used. So for `jackson-core` (and about any other component except databind), just `2.6.7`.
