### ISSUE TITLE
JSON with UTF-8 bom produces Unexpected character

### ISSUE THREAD

**Issue by Tapchicoma** [FasterXML/jackson-core#458]
Jackson-core: 2.9.5.

I am trying to read json with utf-8 bom using following code (in Kotlin):
```kotlin
        val jsonFactory = JsonFactory()
        val content = response.peekBody(DEFAULT_PEEK_BYTE_COUNT)
                .byteStream().bufferedReader().readText()

        try {
            val jsonReader = jsonFactory.createParser(content)
            jsonReader.nextToken()
            if (jsonReader.currentToken == JsonToken.START_OBJECT) {
                while (jsonReader.currentName != "version" &&
                        jsonReader.currentToken != null) {
                    jsonReader.nextToken()
                }
...
```

When reaching line `jsonReader.nextToken()` following `JsonParseException` is produced:
```
Unexpected character ('﻿' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"﻿{"subsonic-response":{
  "status": "ok",
  "version": "1.16.0"
}}"; line: 1, column: 2]
```

Sample json: 
[ping_ok_utf8_bom.tar.gz](https://github.com/FasterXML/jackson-core/files/2002468/ping_ok_utf8_bom.tar.gz)

As I understand Jackson should detect such symbols and handle them right.

**Comment by cowtowncoder** [comment]
In this case the problem is, I think, with your code: `readText()` method is not handling BOM appropriately.
BOM can only exist in byte stream: `String`s and content read via `Reader` should never expose BOM since the concept does not exist at that level.

But besides `readText()` mishandling content, it is not really needed. Creating intermediate `String` is inefficient and unnecessary: parser should be given `InputStream` directly. It can then deal with BOM and handle reading more efficiently as it need not aggregate and decode content separately.

**Comment by Tapchicoma** [comment]
Using `InputStream` directly solves my issue, thank you.
