### ISSUE TITLE
Support for DeserializationFeature.READ_DATES_AS_TIMESTAMPS

### ISSUE THREAD

**Issue by vghero** [FasterXML/jackson-core#461]
Hi.

I'm using jackson 2.9 and trying to disallow parsing of timestamps for `Instant`s.
There exists a setting for _writing_ like `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` which can be disabled. But I'm missing the same settings for parsing timestamps as e.g. ISO-8601 only.
So something like disabling `DeserializationFeature.READ_DATES_AS_TIMESTAMPS` could help here. Otherwise it becomes quite challenging to write strict REST APIs in terms of date parsing.

**Comment by cowtowncoder** [comment]
Ok. First things first: since this repo is for streaming parser/generator, which only handles tokenization, issue would belong rather in `jackson-databind` (if it applies to types in general), or, if Java 8 date/time specific, in https://github.com/FasterXML/jackson-modules-java8.

The challenge here is that of exposing limitations. Features are fine for small number of aspects, but I think ability to limit acceptable input is more generic. 
There is `MapperFeature.ALLOW_COERCION_OF_SCALARS` which does something similar, but is not quite semantically right here. `@JsonFormat(shape=String)` could perhaps be used to limit what may be read, but currently it mostly affects writing. But in combination with `strict` property, that could perhaps work.

So... maybe that'd be the feature to support: strict adherence to declared `shape`. Note, too, that in addition to annotation, it is possible to define per-type shape using `ObjectMapper.configOverrides(Instant.class).setFormat(....)`.

At this point, however, you probably should write a custom deserializer to fail on input other than String.

**Comment by vghero** [comment]
Ah, sorry @ wrong repo :(.

`@JsonFormat` and`strict` sounds reasonable to me. But ok, for now I have to stick with the custom deserializer then, if I understood correctly.

Should we close this issue then and create a new feature request in databind?
