### ISSUE TITLE
not support biginteger when length greate than 16

### ISSUE THREAD

**Issue by damozhiying** [FasterXML/jackson-core#466]
```java

import io.swagger.annotations.ApiOperation;
import java.math.BigInteger;
import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/apis/gateway-conf")
public class ApiGatewayInfoController {

@ApiOperation(value = "获取api网关信息")
	@RequestMapping(value = "/test2", method = RequestMethod.GET)
	public Zoo getGatewayInfo3() throws DcoosException {

		BigInteger bi = new BigInteger("999999999999999889");
		Zoo z = new Zoo(bi,"abc");

		return z;
	}
	@ApiOperation(value = "获取api网关信息")
	@RequestMapping(value = "/test3", method = RequestMethod.GET)
	public BigInteger getGatewayInfo4() throws DcoosException {

		BigInteger bi = new BigInteger("999999999999999889");

		return bi;
	}
}

```js
response body
{
  "bi": 999999999999999900,
  "name": "abc"
}

**Comment by cowtowncoder** [comment]
This looks like Spring framework issue, so it would be necessary to either report this to Spring framework first, or, if possible, isolate and see where the problem lies. For Jackson this would need reproduction without external dependencies like Swagger or Spring framework.

If this turns out to be Jackson problem then:

1. We need unit test that does not depend on Spring or Swagger, AND
2. Issue needs to filed against `jackson-databind`: `jackson-core` is only for streaming API (direct usage of `JsonFactory`, `JsonParser` and `JsonGenerator`

I hope this helps.

**Comment by cowtowncoder** [comment]
No reproduction; may be re-opened with a test case.
