### ISSUE TITLE
Replace toArray(new T[size]) with toArray(new T[0])

### ISSUE THREAD

**Issue by hc-codersatlas** [FasterXML/jackson-core#470]
Might be able to be applied to other Jackson projects too.

https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion (also contains benchmarks).

Could provide some simple performance improvements to Jackson without much work.

**Comment by cowtowncoder** [comment]
I think I saw this article, and findings were interesting. But I must admit I am not convinced it would result in measurable perf improvements since such resizing is quite rare (most storage uses segment-based storage). So I think I'd consider specific changes along with test (jmh benchmark f.ex), if anyone has time and interest.

**Comment by hc-codersatlas** [comment]
Found some time so will create the issues / PR across Jackson. Please review when you can. Thanks for considering!
