### ISSUE TITLE
@JsonIgnore not working with Spring Cloud Greenwich + Spring Boot 2.1.3

### ISSUE THREAD

**Issue by patpatpat123** [FasterXML/jackson-core#529]
Hello Team,

It appears @JsonIgnore is not working with Spring Cloud Greenwich + Spring Boot 2.1.3.
Could you please suggest if there is a specific Jackson version to import?
Is it a known issue?

Thank you

**Comment by cowtowncoder** [comment]
Please do not send user questions on Issue tracker.

And if there is a bug to report, please include actual reproduction.

Finally, questions about Spring components are best sent to spring forums; especially regarding versions to use there. While Jackson users on mailing lists may know answers (and which is why posting there works, but not filing issues), it seems more likely Spring devs and users would. They select versions used and know how Spring uses Jackson. Jackson components know nothing of Spring or its usage.
