### ISSUE TITLE
Change URL in poms to use HTTPS

### ISSUE THREAD

**Issue by ST-DDT** [FasterXML/jackson-core#558]
There are quite a few places in the jackson framework that use http links, these should be replaced with https links.

https://github.com/FasterXML/jackson-core/blob/master/pom.xml#L21
https://github.com/FasterXML/jackson-databind/blob/master/pom.xml#L17
https://github.com/FasterXML/jackson-databind/blob/master/pom.xml#L23

and probably many more

https://github.com/FasterXML/jackson-core/blob/master/pom.xml#L17 is already `https`

**Comment by GedMarc** [comment]
Using HTTP is the best way because of certificate expiration, maven SSL inconsistencies, maintenance not being performed, revocation lists being updated, and many many more.

While it is a nice idea, and does fit most portfolio's, for open source fast moving projects, SSL in POM files is nothing more than a serious and very destructive practice.

Good for in house projects, terrible for maven open source.

**Comment by ST-DDT** [comment]
> Using HTTP is the best way because of certificate expiration, maven SSL inconsistencies, maintenance not being performed, revocation lists being updated, and many many many MANY more.

If github's certificate will ever expire, then we have a hell more problems. I'm not even sure whether you can actually access it via http aside from being redirected directly to https.

Then at least https for the project's urls (outside of scm), because these will be shown in maven's site and other similar reports and leave a bad first impression to those that read them.

**Comment by ST-DDT** [comment]
> There is a reason why it is HTTP. Try and understand the reason.

I do. Not working HTTPS is inconvient/causes trouble.

But would you visit your bank-site if the don't serve it via HTTPS?
There is a good reason why it failed.

--------------

> Sonartype official workaround for using SSL - https://support.sonatype.com/hc/en-us/articles/213465038-Fix-https-repository-blocking-by-PKIX-path-building-failed

The link you posted (and all search results I could find) explain how to "whitelist" the conflicting certificate. They do not recommend or even mention a downgrade to HTTP.
As for the "turn off the entire HTTPS" validation, I would consider it a very dangerous workaround at best.

**Comment by GedMarc** [comment]
Very dangerous yes.
Research it please, like I said, don't have the time or urge to google for you.

We all keep our repository on HTTP because we have all felt the burn when SSL slips, wasn't a month ago no one could deploy to Sonartype Central for 4 days because the SSL cert went invalid and all overrides had to be done on the CI's

No, you do not put HTTPS into Maven artifacts. Not on fast moving, fast deploying, open source projects.
If you deploy once every 6 months, fine whatever, an SSL break isn't the end of the world.
If you are a fast moving open source project, you cannot allow 3rd party failures to impact your deployment cycle.

Turning off the HTTPS validation turned out to be the only way (check you stack overflows, check your maven error imports, look at the thousands of complaints about it).

Sorry, but full on disagreement with you. Not in Maven, Not on fast moving projects, not with such a dependency on a 3rd party.
No 3rd party is immune, and every 3rd party has been affected by it, and many many open source developers have felt the pain.,
You will find this intentional "problem" in almost all repositories that have deployment cycles on-demand or less than 6 months.

Not going to happen.
