### ISSUE TITLE
Allocating a JsonParser for a byte[] looks inefficient

### ISSUE THREAD

**Issue by CodingFabian** [FasterXML/jackson-core#593]
When profiling one of our Kafka consumers, I noticed that for every message a new HeapByteBuffer is allocated. This was surprising to me, because I thought they would be re-used, but it seems that the `JsonFactory` actually uses a new `InputStreamReader` for every byte array. And this InputStreamReader will use HeapByteBuffers for its internal buffering.

Is this something Jackson could do more elegantly by reusing the buffers? There seems to be no obvious way of reusing StreamDecoder, or InputStream reader, but since the source is known to be a byte array, there should be something better 

Jackson version is 2.10.1.
<img width="975" alt="Screenshot 2020-01-14 at 12 09 53" src="https://user-images.githubusercontent.com/176132/72340295-3e9c2100-36c8-11ea-806c-ba7a763c4c43.png">
(The API called in this screenshot is ObjectMapper.readValue(byte[]), but there seems to be no way to call this more efficiently since all calls end up in com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructReader())

**Comment by CodingFabian** [comment]
We do have `CANONICALIZE_FIELD_NAMES` disabled,
that is why `com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(int, ObjectCodec, ByteQuadsCanonicalizer, CharsToNameCanonicalizer, int)` builds a `ReaderBasedJsonParser` not a `UTF8StreamJsonParser`. The latter potentially might be faster. The comment however suggests that the reader based json parser should be faster.

The byte array we deserialize is just a few bytes long. the json effectively is `{"key":"value"}`

**Comment by CodingFabian** [comment]
Initial benchmarking shows that if I would enable `CANONICALIZE_FIELD_NAMES` the performance would be 5x higher, because of the UTF8StreamJsonParser despite the additional work for canonicalizing field names

**Comment by cowtowncoder** [comment]
Correct: it is typically a bad idea to disable `CANONICALIZE_FIELD_NAMES`.
So I would not do that unless there is a particular reason to do it.
Disabling intern()ing with the other setting has less of performance impact (although with 2.x and `jackson-databind`, POJOs, there is some modest performance penalty -- 3.x changes this so that there isn't).
Canonicalization here simply means that a symbol table is reused across reads, to avoid allocations of symbol objects (for Reader-backed just `String`s, for byte/InputStream object that has byte-level match as well as String). It is a performance optimization and is on by default, only to be disabled if something indicates that there are issues -- the main example I can think of is when decoding content where primary keys are always unique, like UUIDs. In that case maintaining a symbol table only adds overhead.

I am not sure where suggestion was made that Reader-based parser could be faster, but unless you get `Reader` already (and would need to do extra work for anything else), byte-based input sources are faster for Jackson: I have not seen a benchmark ever showing anything else, not even when "reading" from memory source where `Reader` already gives decoded characters.

The reason for superior performance for `byte` backed sources with Jackson core (if passing `byte[]`, no `InputStream` is created normally) is that it will use most compact input (least memory impact), and decode most names directly into symbol with one pass and no memory allocations. This is the main optimization path as well, tweaked much more than any other code path (I have spent some time with char[]/Reader backend too, just not nearly as much).

Now, the reason why actual `Reader` is created for byte-sources if canonicalization is NOT enabled (regardless of interning): without canonicalization there is no optimized path way to avoid intermediate representations, allocations; and some of costs otherwise amortized over multiple decodings will be paid for every name. This means that use of `Reader` will be faster.

Creation of `ByteBuffer` is something JDK does, then, Jackson does not use `ByteBuffer` for anything (due to clunky API, inefficient access -- there's very little to like about it unfortunately). While there is a more optimized UTF-8 decoding reader used by some format backends (CSV at least, maybe YAML, Properties), this is secondary path so I don't think there is much benefit to trying to make it faster.

I hope this makes bit more sense.

**Comment by CodingFabian** [comment]
@cowtowncoder it does. and thank you very much for this elaborate answer (I did not really expect that)
The reason for disabling canonicalization was overflowing the symbol table. But it has been years since we did that and new benchmarks could not reproduce the benefit, so we reverted it.
If the reader is indeed the uncommon path, I agree, there is no need for further optimization.
Thank you.

**Comment by cowtowncoder** [comment]
Actually couple more thoughts...

First, bit surprised by 5x speed up, just the magnitude (I would expect it to be faster): probably these are quite small documents? (so overhead of JDK creating buffers for stream reader, f.ex, is much bigger).

Another thing is that over time handling of symbol table filling has been improved incrementally, so that even in sub-optimal case of (tens of) thousands of unique names, memory usage is bounded. There were also some hashing improvements associated with it. This could explain why handling is not problematic any more even if input hadn't changed (of course many other possibilities too).

Anyway -- this is one area that always fascinates me. I wish I had better tools for analyzing performance these days, as JDK -Xhprof does not work very well but none of the other tools have worked any better for kinds of tests I do.

**Comment by CodingFabian** [comment]
Yes, they are small. With Kafka you use a small key and a large payload. You look at the key to figure out if you want the message. The code that showed up as a hotspot was the code looking at those about 1kb keys that are json serialized.

For me, I try to make minimalist JHM benchmarks. In this case a very simple small JSON as bytes and then one ObjectMapper using a default factory and one with a disabled feature flag to trigger the two different code paths.
It really seems to be the heap bytebuffer allocation that tips the scale. It also allocates 8x as much memory when going down the `Reader` path.

**Comment by cowtowncoder** [comment]
Yeah, that big buffer allocation for readers/streams by JDK has for years been huge overhead, and main reason for custom implementations of certain objects that otherwise I'd leave as-is (like  UTF-8 Reader).
And I am guessing that your test case uses even smaller messages than 1kB? (jvm-benchmark for example uses rather small, 400b as json)
