### ISSUE TITLE
Serializing an object to JSON and then Deserializing from a String coming through Redis

### ISSUE THREAD

**Issue by wasmake** [FasterXML/jackson-core#665]
Hello,
We are having some issues with jackson at my development team.

**Some non-important context**
We are pretty new with jackson and we had several issues over the past, but we always had tried to solve them with what we got over the internet and with past-problems solved over StackOverflow.

**Useful information**
We are parsing Java instanced objects to JSON so we can send them over redis as Strings and then get them through the pub/sub system to get them again as objects of the original type on the other end.

We have 2 fields where in each one of them represents different objects:

Data: a ChannelMessage object.
String senderName, message;
Enum:ServerType serverType;

Metadata: a RedisMetadata object.
String id, channelName, serverId;
Enum:MessageType type;

So our JSON should look something near this:
`{
  "data": {
    "senderName": "PixelDev1729",
    "message": "asd",
    "serverType": "HUB"
  },
  "metadata": {
    "id": "1bba40f5-74ed-4ab8-ad81-83078ac11421",
    "channelName": "global-chat",
    "serverId": "b4409522-6a97-47f5-ad75-661ed86c52e8",
    "type": "SEND"
  }
}`

**Several headaches**
We've tried using ObjectNodes writing values as String from the object.

We got a really messed up JSON string with lots of escapes (backslashes).

`{"data":"{\"senderName\":\"PixelDev1729\",\"message\":\"asd\",\"serverType\":\"HUB\"}","metadata":"{\"id\":\"e0f77d09-cafa-4ff5-b553-0f0dc4bb76e3\",\"cha|
nnelName\":\"global-chat\",\"serverId\":\"9f10cf0b-d3eb-4804-98aa-92d747d75f5e\",\"type\":\"SEND\"}"}`

1.- "No string-argument constructor/factory method to deserialize from string value (Colum: 1, Line: 1)." in which from my expertise I can say the JSON string Jackson is getting is invalid.

So different approach...

Using `jsonString.replaceAll("^\"|\"$|\\\\", "");` to the same string we got first.

Resulting on an almost valid JSON but still invalid since we got some double quotes missing.
`{"data":**"**{"senderName":"wasmake","message":"sadasdas","serverType":"VALHEIM"}**"**,"metadata":**"**{"id":"410c429c-06a4-466a-bce2-5edd63fabe17",|
"channelName":"global-chat","serverId":"640d01c3-5b13-4dcf-84bc-1d6b2987b333","type":"SEND"}**"**}`

2.- Unexpected character ('s' (code 115)): was expecting comma to separate Object entries

The double quotes doing weird things with our first field from data "**S**enderName".

CODE:
How we are serializing the object to JSON with jackson to send the message through Redis:
![image](https://user-images.githubusercontent.com/8813159/104827760-06717600-5827-11eb-8cd6-48554db93c49.png)

How we are trying to deserialize the JSON with jackson to get the object from the message we get from redis:
![image](https://user-images.githubusercontent.com/8813159/104827779-45073080-5827-11eb-84fc-47673c395b69.png)

The RedisMetadata class:
![image](https://user-images.githubusercontent.com/8813159/104827795-5cdeb480-5827-11eb-9595-c9326ca59e3f.png)

Console log:

![image](https://user-images.githubusercontent.com/8813159/104827799-66681c80-5827-11eb-8801-4c107df0dcb6.png)

![image](https://user-images.githubusercontent.com/8813159/104827801-6d8f2a80-5827-11eb-9170-80635c74110f.png)

We would really appreciate a helping hand since we've tried everything and with no luck,
thanks in advance!

**Comment by cowtowncoder** [comment]
Ok, first things first: for usage questions, the right places are:

1. Mailing lists (https://groups.google.com/g/jackson-user)
2. Chat: https://gitter.im/FasterXML/jackson-databind

and issue tracker should be only use for reporting issues or requesting/suggesting new features. Having said I can probably suggest some things.

First of all is that I am not sure if you could not use actual Plain Old Java Objects (POJOs): `JsonNode` can be useful if structure varies and is not highly structured, but in your case you seem to have value objects in place. Metadata at least is regular type; but maybe value type varies.

But if using `JsonNode`, mismatch you have is that you are first serializing Java object as JSON String, and then adding it in `ObjectNode` as value: JSON-in-JSON, resulting in double-escaping (as well as unnecessary work). So instead of

```
node.put("data", mapper.writeValueAsString(data));
```

you probably want to use

```
node.putPOJO("data", data);
```

and same for "metadata".

(under the hood this uses `ObjectMapper.valueToTree()` to create `JsonNode` out of Java value)

A smaller optimization, too, is to prefer `writeValueAsBytes()` for ObjectNode (instead of `writeValueAsString()`), as that is more efficient -- but that does not change semantics.

Now as to using POJO: looks like you could probably use a generic "envelope" class to avoid JsonNode; something like

```
public class Message<T> {
   public RedisMessageMetadata metadata;
   public T data;

   // and/or getters, setters instead of public fields
}
```

although usage gets slightly more complicated on deserialization side (serialization would work by just passing value, but deserialization you would need to use either `TypeReference` or construct `JavaType`).

I hope this gets you past the initial hurdle.

**Comment by cowtowncoder** [comment]
Hoping above helps: since this is a usage question, follow-ups please on chat/mailing list. Closing.
