### ISSUE TITLE
jackson serialize Object make OOM

### ISSUE THREAD

**Issue by violetgo** [FasterXML/jackson-core#737]
hi, we use version `2.12.5` to serialize json.
and i have try handle HttpServletRequest object to string .
and print it for easy track issues. 

but when i try serialize HttpServletRequest instance to String . it make OOM
I know maybe http request is to large . and also i can delete this print to fix it .
but i think it still dangerous 

i got the heap dump and this serialize action make large than 500M .
and stack is large than 4000+

![image](https://user-images.githubusercontent.com/5086059/147817270-cc730fdb-beda-4b06-8c03-eae439e0b91d.png)
![image](https://user-images.githubusercontent.com/5086059/147817294-d8683841-dae2-487a-9196-f4d5dbe1950d.png)

so , can we have any method to limit serialize size ? 
like object deep ? or string size ?

any answer will got help. wait for your reply.

thanks~

**Comment by cowtowncoder** [comment]
At this point if you ask Jackson to serialize something, it does so. It is up to you to figure out what to serialize.
Since attackers typically have no way to force serialization, I would not consider this as a security issue either.

In theory it'd be possible to add configurable limits for things like total serialized output size but there isn't anything yet; and if something was to be added it would need to be designed for different kinds of limit.

But until then, it would be possible for you to implement specific kind of `Writer` or `OutputStream` that keeps track of amount that has been written, throw exception if maximum exceeded. Then pass that Writer/OutputStream as target to Jackson.
Currently this is the only way to catch issue that I can think of.

**Comment by violetgo** [comment]
OK, thanks a lot . and I got the serialize object is a lot of `A`
![image](https://user-images.githubusercontent.com/5086059/147998776-cd0eb6c6-ee18-4645-b91c-057ddd83cd82.png)
so , i think it is not right request .
anyway , i will try limit the serialize object size. 
and can you help told me how can i custom-made `Writer` or `OutputStream`  implement? how can i let jackson use my specific kind class ? 
any API document can finger out it ?
thanks~

**Comment by cowtowncoder** [comment]
You would simply implement Writer or OutputStream that delegates to another one and keeps track of how much content has been output; throwing exception if maximum amount is exceeded. Perhaps some frameworks (Guava?) even have implementations like this.
Jackson `JsonFactory` (and `ObjectMapper`, `ObjectWriter`) accept Writers and OutputStreams: they are the usual things to use -- serializing as a String for example is more of an anti-pattern.

**Comment by violetgo** [comment]
ok ,thanks a lot , and I try to implement JsonFactory  and use `new ObjectMapper(new CustomJsonFactory());`
then I can overwrite `createGenerator` method.
then I can get write event and try record write string . seem work ~
thanks again ~
