### ISSUE TITLE
For Jackson 2.14, make Java 1.8 the min version supported

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#746]
https://github.com/FasterXML/jackson-core/issues/577#issuecomment-1084956488

**Comment by cowtowncoder** [comment]
As per our discussion, this is a possibility. Would it be possible for you to bring this up on `jackson-dev` (https://groups.google.com/g/jackson-dev), explaining specific need at this point? I don't mind proposing these things but it is often best for contributors to ask for it since there is given need; and also if I propose something there may be less actual discussion if everyone feels I will just do it anyway. :)

I will definitely follow and participate in the discussion, either way.

**Comment by pjfanning** [comment]
https://groups.google.com/g/jackson-dev/c/xAogwxgHgvU

**Comment by cowtowncoder** [comment]
Yes, will be done as per #745.
