### ISSUE TITLE
Schubfach classes using GPL2 license

### ISSUE THREAD

**Issue by christopher-cudennec** [FasterXML/jackson-core#908]
Hello people of jackson-core! 😃 

Our license scanner found some classes within your project that use the [GPL-2.0-with-classpath-exception](https://fossa.com/blog/open-source-software-licenses-101-gpl-v2/) license. Since this is a copy left license it is not possible to use these classes in our commercial products.

The affected classes are related to the Schubfach algorithm in the `com.fasterxml.jackson.core.io.schubfach` package:
* DoubleToDecimal
* FloatToDecimal
* MathUtils

I assume that many commercial products are affected by these classes. Is there a way to mitigate the issue? I guess it also conflicts with your Apache 2 license, doesn't it?

Cheers,

Christopher

**Comment by pjfanning** [comment]
Could yo have a look at https://softwareengineering.stackexchange.com/questions/119436/what-does-gpl-with-classpath-exception-mean-in-practice?

The top answer has:
```
It clearly states that the code under the license is (L)GPL, but anything using that code can follow whatever license they'd like. No ifs, ands, or buts.
```

This is endorsed by Anthony Green, one of the authors of the classpath exception.

**Comment by christopher-cudennec** [comment]
Thanks for pointing that out. 🌷 
Will close the issue. 👍

**Comment by pjfanning** [comment]
If you are still concerned, these classes are not used in the default mode. You need to enable the USE_FAST_DOUBLE_WRITER feature.

If you don't use this feature, you could try excluding those classes - for instance, if you build an assembly jar (aka fat jar, shaded jar, etc.).

**Comment by christopher-cudennec** [comment]
Thanks for your help and opinion. I know about the option to exclude specific classes but it would not be my favourite one. ;)

**Comment by aleguenn** [comment]
Hello @pjfanning, @christopher-cudennec, @cowtowncoder 

Like Christopher, I ran a scanner on jackson 2.14.2 source files and found the 3 files that use the GPL-2.0-with-classpath-exception license. I was about to enter a similar issue when I found this one by Christopher.
I also read the answers, and the discussion on stackexchange mentioned above, including the comment by Anthony Green.
However, I'm still concerned by a few points:
- It's not made clear where the code is coming from. Presumably from the OpenJDK project (i.e. https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/jdk/internal/math/MathUtils.java).
  It's not mentioned in release-notes/CREDIT-2.x or in src/main/resources/META-INF/NOTICE.
- The fact that jackson-core is not entirely under Apache 2.0 anymore because of the Schubfach code is not mentioned in the LICENSE file. Moreover, the header file the Schubfach code states that a copy of the GPL license should be included (it's not currently).
- Maybe more importantly, the classpath exception refers to linking with "**independent modules**", and here, it is arguable whether jackson-core _itself_ is still an independent module with respect to that code, which is not in a separate library. Instead, the code is somewhat commingled with jackson source code directly, so it is not clear if the classpath exception is still applicable or not. Note that the openjdk license specifically warns against commingled code with different licenses (although using a different scenario as an example): See https://openjdk.org/legal/gplv2+ce.html:
  > Oracle facilitates your further distribution of this package by adding the
  > Classpath Exception to the necessary parts of its GPLv2 code, which permits
  > you to use that code in combination with other independent modules not
  > licensed under the GPLv2. However, note that this would not permit you to
  > commingle code under an incompatible license with Oracle's GPLv2 licensed
  > code by, for example, cutting and pasting such code into a file also
  > containing Oracle's GPLv2 licensed code and then distributing the result.

Maybe a cleaner solution would be to put that code in a separate jackson-core-schubfach library, in its own repository, with its own license? What do you think?

Regards,
Alain

**Comment by pjfanning** [comment]
v2.14.3 and v2.15.0 (including the RC releases) removes the problematic code

**Comment by aleguenn** [comment]
@pjfanning, thank you very much for the clarification.
I had a quick look at the "Schubfach" files and their history (looks like great work, btw!).
Apparently, there are two variants of those files:
-One version that was integrated in OpenJDK (the one that jackson 2.14.2 incorporated), under GPLv2-with-classpath-exception.
-One version that is hosted at https://github.com/c4f7fcce9cb06515/Schubfach/ , under a MIT license.
If I understood correctly the history in jackson, you started from the latter, migrated to the former, then reverted to the latter version for 2.15.0 and 2.14.3, right?
The work was originally by Raffaello Giulietti (who had it incorporated in OpenJDK),
and the version from https://github.com/c4f7fcce9cb06515/Schubfach/ actually credits him in the copyright header as the copyright owner (while the OpenJDK version has Oracle as the copyright owner).

I hope I'm not being too picky, but I still have two questions:
-Was the version at https://github.com/c4f7fcce9cb06515/Schubfach/ actually released by Raffaello Giulietti himself?
 That github repository is owned by user "c4f7fcce9cb06515", which is not easily identifiable.
 Note that Raffaello Giulietti is also present on github at https://github.com/rgiulietti, so it is a bit strange.
-Did Raffaello Giulietti signed the contributor agreement for jackson?
 As the copyright owner, he probably is the only one that can grant the rights described in the CLA (eg, joint-ownership), isn't he? (as per section 5 of the CLA).

Regards,
Alain

**Comment by pjfanning** [comment]
2.14.2 change was a mistake. The code in every version of Jackson is based on https://github.com/FasterXML/jackson-core/blob/1976c0dc7f13fbc4f22e9529d1221fc39091cafe/src/main/java/com/fasterxml/jackson/core/io/schubfach/DoubleToDecimal.java#L56 (similar comments appear in the other Schubfach classes).

https://github.com/c4f7fcce9cb06515/Schubfach/ is the source of these files.

The license header is super permissive on these files. 

```
 * Copyright 2018-2020 Raffaello Giulietti
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
```

I think we have abided by these terms.

@cowtowncoder would you insist on a CLA? - should we planning to remove this code altogether?

**Comment by cowtowncoder** [comment]
@pjfanning If it was easy to get CLA that'd be nice, but as far as I can see, this should suffice without CLA.

As to removal, what is the relationship b/w code discussed here and FastDoubleParser?

**Comment by pjfanning** [comment]
> 
> As to removal, what is the relationship b/w code discussed here and FastDoubleParser?

The Schubfach classes are used for fast writing of floats/doubles  (NumberOutput) while FastDoubleParser is used in NumberInput (also optionally).

**Comment by cowtowncoder** [comment]
Ahh. And we do not necessarily have performance numbers yet for writing side either (maybe I should go ahead and do those).

Now: my opinion is that either code should be included and used, if possible; if not, I don't really want to design add-on packages for `jackson-core` due to complexities it entails.
That is: add-ons outside core are fine but I would not want to try to design pluggable architecture for pluggable low-level decoding/encoding. That would very likely to be complex and confusing to users.

**Comment by cowtowncoder** [comment]
Oh and wrt @aleguenn's suggestion:

```
Get confirmation that the MIT version at https://github.com/c4f7fcce9cb06515/Schubfach/ was actually released by Raffaello Giulietti himself, and not a rip-off of his work released by someone else with a seemingly more convenient license to circumvent the gpl-with-classpath-exception 
```

That sounds like a good idea if it could be done. I certainly would not want to abuse freely available code in any way.

**Comment by pjfanning** [comment]
That code in c4f7fcce9cb06515 was written long before the JDK code.
