### ISSUE TITLE
Gradle metadata for `jackson-core` `2.15.0` adds dependency on `ch.randelshofer:fastdoubleparser`

### ISSUE THREAD

**Issue by chrisr3** [FasterXML/jackson-core#999]
We have updated our Gradle build to use Jackson 2.15.0, but have noticed that
```gradle
'ch.randelshofer:fastdoubleparser:0.8.0'
```
has now been included as a transitive compile dependency. This appears to be due to:
```json
"dependencies": [
    {
        "group": "ch.randelshofer",
        "module": "fastdoubleparser",
        "version": {
            "requires": "0.8.0"
        }
    },
```
being included in `jackson-core-2.15.0.module`, which unfortunately is clobbering the contents of the POM.

**Comment by pjfanning** [comment]
Honestly, gradle should support a flag where you force pom usage. Just in case.

**Comment by cowtowncoder** [comment]
I think this is something @jjohannes needs to be looped in.

**Comment by chrisr3** [comment]
> Also... I wonder why this did not come up during our RC phase. :-(

Perhaps all the testing was with Maven?

**Comment by cowtowncoder** [comment]
@chrisr3 Project itself does not use Gradle, but I'd have expected user base has many Gradle users. But maybe use of Module metadata (GMM) is not quite as wide-spread yet.

But honestly I am getting quite disillusioned by usefulness of RC phase. For any issues that are reported (there are some) there are multiple that aren't until .0 lands. And I am not sure longer RC phase would help either.

Having some integration tests for Gradle side would help of course. I think `jackson-integration-tests` have some, come to think of that. But not using GMM, I think.

**Comment by pjfanning** [comment]
Could we reconsider the gradle modules? Gradle works fine with poms. I don't see the real benefit and all this downside about testability of the gradle modules. I haven't added the gradle modules to the Scala module - in large part because I'm bewildered by why do they even exist.

**Comment by chrisr3** [comment]
> Could we reconsider the gradle modules?

Gradle modules claim to provide a "richer" metadata view than POMs do. However, Jackson clearly needs to support both Maven and Gradle _equally_, and so I don't see that "richer" Gradle metadata being of any use to you. (And particularly seeing as that metadata is wrong here anyway...)

**Comment by cowtowncoder** [comment]
Addition of Gradle module metadata (which Jackson does not use, but provides) was a contribution, meant to improve interoperability. Similar to how OSGi metadata is provided; or Java 9+ module info. As long as there are community members willing to help, I think it makes sense to offer this. And as long as information is not net-negative (breaking use cases).

**Comment by pjfanning** [comment]
The real impetus is behind SBOMs to provide the richer metadata - like the digests of the dependency jars used in the build. SBOMs are not tied to one build tool - the aim is to support them across the industry. But of course, there are competing SBOM standards (CycloneDX and SPDX, hopefully no other ones).

**Comment by cowtowncoder** [comment]
Sounds like SBOM could provide improvements in future and as such should be supported. And maybe remove/reduce need for earlier tool-specific metadata approaches.

**Comment by jjohannes** [comment]
Sorry about this. I also could have thought of this effect when we first encountered problems in combining the `maven-shade-plugin` and the `gradle-module-metadata-maven-plugin`.

I think I would have to find a solution in the plugin. To somehow react to the _shade_ plugin and take it's configuration into account.

Just as reminder, this is why we publish the metadata - version alignment through the BOM:
https://blog.gradle.org/alignment-with-gradle-module-metadata

This is something you can not express in POM. Otherwise, I agree that there would be no point in adding the Gradle Metadata on top. I know at least one other library (JUnit5) that also has this feature (but the build with Gradle). The difference here is that we do this although the build is Maven. It was a bit of an experiment to do this back in the day, but it seemed to have worked flawlessly for the first 2 years or so. The issue now is that the _shade_ plugin came into play and combining plugins in Maven is tricky, as there is no clear concept in Maven how plugins can/should interact.

But anyway, if you feel it's not worth the trouble anymore, you could also remove the Gradle Metadata publishing again. Just let me know, as Jackson is the main reason right now for me to further extend that Maven plugin.

What I would do (if I hopefully find the time this weekend):
1) Extend the Gradle integration test we already have to catch such issues
2) Investigate how I can improve the plugin to interact with the _shade_ plugin. And ideally find a satisfying solution and publish a new version.

**Comment by pjfanning** [comment]
A solution where we can list dependencies to ignore in the gradle module might be an option.

**Comment by pjfanning** [comment]
Seems workable to me

**Comment by jjohannes** [comment]
Done. I found another issue in the plugin (handling of optional dependencies) through the test. Fixed now and new version is released.

I listed what needs to be done in the different repos in the integration test PR: https://github.com/FasterXML/jackson-integration-tests/pull/19

**Comment by cowtowncoder** [comment]
I started preparing for fixes with https://github.com/FasterXML/jackson-bom/issues/63 that upgrades GMM plugin version in parent pom.
